import {createClient} from '@/lib/supabase/server';
import {NextResponse} from 'next/server';

export async function POST(request: Request) {
  try {
    const supabase = await createClient();

    // Verify authentication
    const {data: {user}, error: authError} = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({error: 'Unauthorized'}, {status: 401});
    }


    // Get id from profiles table
    const {data: studentProfile, error: profileError} =
        await supabase.from('profiles').select('id').eq('id', user.id).single();

    // Debug logging
    console.log('=== PROFILE DEBUG ===');
    console.log('User ID:', user.id);
    console.log('User Email:', user.email);
    console.log('Profile Error:', profileError);
    console.log('Profile:', studentProfile);
    console.log('Profile ID:', studentProfile?.id);
    console.log('====================');

    const body = await request.json();
    const {accuracy_score_0to1, feedback, question, skill_id} = body;

    // Prepare insert data
    const insertData: any = {
      accuracy_score_0to1,
      feedback,
      question,
      skill_id,
    };

    // Add id if found
    if (studentProfile?.id) {
      insertData.student_id = studentProfile.id;
      console.log('✓ Including student_id in insert:', studentProfile.id);
    } else {
      console.log('✗ No id found - will insert NULL');
    }

    // Insert the assessment question score
    // Note: assessment_id will be auto-generated by the database
    const {data, error} = await supabase.from('assessment_questions_score')
                              .insert([insertData])
                              .select();

    if (error) {
      console.error('Supabase error:', error);
      return NextResponse.json({error: error.message}, {status: 500});
    }

    return NextResponse.json({success: true, data});
  } catch (error) {
    console.error('Error in assessment API:', error);
    return NextResponse.json({error: 'Internal server error'}, {status: 500});
  }
}
